#!/usr/bin/env python3
"""The launch film's palette, read from film/arcana.html and film/core.js (not retyped)."""
import json, re, sys, subprocess, os
film, out = sys.argv[1], sys.argv[2]
html = open(os.path.join(film, 'arcana.html')).read()
core = open(os.path.join(film, 'core.js')).read()

def line_of(src, needle):
    i = src.index(needle)
    return src.count('\n', 0, i) + 1

def palette(name):
    m = re.search(r'const %s = makePalette\(\{(.*?)\}, \'(\w+)\'\);' % name, html, re.S)
    body, look = m.group(1), m.group(2)
    d = {}
    for k, v in re.findall(r"(\w+):\s*(\[[^\]]*\]|'[^']*'|null)", body):
        if v == 'null': d[k] = None
        elif v.startswith('['): d[k] = re.findall(r"'([^']*)'", v)
        else: d[k] = v.strip("'")
    d['_core_look'] = look
    d['_source'] = 'film/arcana.html:%d' % line_of(html, 'const %s = makePalette' % name)
    return d

angles = [float(x) for x in re.search(r'angles = \[([^\]]*)\]', html).group(1).split(',')]
reg = json.loads(re.search(r'const REG = (\[\[.*?\]\]);', html).group(1))
cell = float(re.search(r"cell: o\.cell \|\| ([\d.]+)", html).group(1))
maxcov = float(re.search(r"maxCov: o\.maxCov \?\? ([\d.]+)", html).group(1))
fl = palette('FIRST_LIGHT'); cs = palette('CARD_STOCK')
import math
plates = []
for k, ink in enumerate(fl['inks']):
    plates.append({
        'order': k + 1, 'ink': ink,
        'name': ['cornflower (the blue overhead)', 'lavender (the lilac in the air)',
                 'rose (rising from below the horizon)', 'apricot (the dawn)'][k],
        'screen_angle_rad': angles[k], 'screen_angle_deg': round(math.degrees(angles[k]), 1),
        'misregistration_px': reg[k],
    })
ffp = subprocess.run(['ffprobe', '-v', 'error', '-show_entries',
    'format=duration,size:stream=codec_name,width,height,r_frame_rate,sample_rate,channels',
    '-of', 'json', os.path.join(film, 'out/arcana-final.mp4')], capture_output=True, text=True).stdout
doc = {
    'title': "Launch film — 'Everyone's question, drawn' (arcana — everyone's question)",
    'look': 'riso prints in four fluorescent-leaning inks on warm pearl stock (the twelve places, the gather, the answers, the sign-off sky); the cards in the app\'s own pen line on cotton stock with one gold (riffle, back, the Star)',
    'app_colours_the_inks_reproduce': {
        'note': "the film's own comment (arcana.html:30-31) says the inks print the app's sky: skyBlue #ccdbf5, lilac #e0d8f7, rose #fdddcc, dawn #ffe0b0 on pearl. The app's Palette.swift has lilac #E0D7F7 and rose #FDDDDC (the film's comment has a typo for rose), and its pearl #F9F7F2 is cooler than the film's paper #f6f1e7.",
        'Palette.skyBlue': '#CCDBF5', 'Palette.lilac': '#E0D7F7', 'Palette.rose': '#FDDDDC', 'Palette.dawn': '#FFE0B0', 'Palette.pearl': '#F9F7F2'},
    'FIRST_LIGHT (places, riso)': fl,
    'CARD_STOCK (the deck, ink)': cs,
    'riso_plates': {
        'printed_in_order': plates,
        'halftone': {'cell_px': cell, 'dot_radius': 'cell x 0.62 x sqrt(coverage)', 'coverage_cap': maxcov,
                     'jitter': '0.07 cell', 'blend': 'multiply', 'ink_alpha': 0.95,
                     'coverage': 'each plate is drawn as grey on white, sampled on a grid of one cell (luma 0.299/0.587/0.114)',
                     'source': 'film/arcana.html:%d-%d; film/core.js:%d' % (line_of(html, 'const REG ='), line_of(html, 'printPlate(c, P,'), line_of(core, 'function printPlate'))},
    },
    'stock': {'paper_fill': fl['paper'], 'grain': '1400 specks of shade(paper, .5) at 6% alpha, size 1.6 (core.js paper())',
              'card_stock_grain': '900 specks of CARD_STOCK.shade at 7% alpha, size 0.9, clipped to the card 226 x 400 r3',
              'source': 'film/core.js:%d; film/arcana.html' % line_of(core, 'function paper(')},
    'gold_leaf_in_the_film': 'flat #c9a82f, hatched goldLit #ecce6e @55% (angle 0.8) and goldDeep #8a6819 @35% (angle -0.75); the app uses a four-stop gradient instead',
    'type': {'signoff': "ARCANA, bold Didot ('Didot, \"Bodoni 72\", serif'), 108 px on the 1080 frame (SHORT x 0.1), letter-spacing 32.4 px (size x 0.3), laid letter by letter in gold that cools to ink, then the title's light passes once",
             'cards': 'Didot: numeral bold 15 tracking 3.2; name bold 17 tracking 1.4 uppercase; essence italic 12.5 in oxblood #8c2e25'},
    'format': {'frame': '1080 x 1080 (1:1)', 'drawn_fps': 12, 'output_fps': 24, 'frames': 256, 'duration_s': 21.33,
               'video': 'H.264 yuv420p crf 18, +faststart', 'audio': 'AAC 48 kHz stereo 192 kbps, two-pass loudnorm -16 LUFS / TP -1.5',
               'ffprobe': json.loads(ffp) if ffp else None},
    'where': {'mp4': 'film/out/arcana-final.mp4 (gitignored, not committed; regenerated by cd film && npm install && ./make.sh). The posted file is ~/Downloads/arcana-launch-2.mp4 per the project notes.',
              'copy_in_assets': 'brand/film/arcana-launch-film.mp4', 'frames': 'film/out/arcana-frames/0000-0255.png',
              'source': 'film/arcana.html (+ core.js by Alexey Fateev, MIT), film/README.md, commit 14b7fc6 (2026-09-28)'},
    'timeline': [
        [0.00, 1.50, 'window', 'riso', 'a city at first light, one window lit; it rings'],
        [1.50, 1.00, 'pier', 'riso', 'the end of a pier, a lamp, someone facing the sea'],
        [2.50, 0.75, 'crossroads', 'riso', 'a signpost at a fork in the road'],
        [3.25, 0.75, 'door', 'riso', 'a doorway lit gold, someone on the step with a case'],
        [4.00, 2.67, 'montage', 'riso', 'bench, clock, boat, hill, bridge, lighthouse, field, ring: faster and faster'],
        [6.67, 1.50, 'gather', 'paper', "every place into the wheel's twelve houses; the wheel turns and all of it goes into the light"],
        [8.17, 0.08, 'flash', 'paper', 'the cut'],
        [8.25, 2.58, 'riffle', 'ink', 'the deck riffles past, slows; the back; the turn'],
        [10.83, 3.00, 'star', 'ink', 'the Star writes itself in gold that cools to ink'],
        [13.83, 4.00, 'answer', 'riso', 'the places again; stars come out in the day sky'],
        [17.83, 3.50, 'signoff', 'riso', "ARCANA laid letter by letter; the title's light passes"],
    ],
    'timeline_source': 'film/arcana.html:%d' % line_of(html, '// t (s)   dur'),
}
json.dump(doc, open(out, 'w'), indent=1, ensure_ascii=False)
print('film palette →', out)
